### ISSUE TITLE
Unnecessary usage of attr_accessor

### ISSUE THREAD

**Issue by jerryjohnjacob** [sherfin94/resume-maker#3]
In the [resume maker](https://github.com/sherfin94/resume-maker/blob/master/lib/resume_maker.rb#L7), there are attribute accessors specified for the handlers. But if you really look at it, these are not details that need to be exposed outside this object. One of the ideas of OOP is encapsulation - keep internal stuff internal.

**Comment by sherfin94** [comment]
I have added more return values and tested the same with more expects on [this](https://github.com/sherfin94/resume-maker/commit/b9248559d9eada42945dba2289171ccd165de413) commit.
